#!/usr/bin/env node
/**
 * apply-nav.js — put the toggle navigation on every page.
 *
 * The main site had a sticky pill with hover dropdowns; the campaign page had a
 * compact bar with a toggle panel. Same links, two interaction models. This
 * makes the whole site use the campaign page's navigation — logo on the left, a
 * toggle on the right, one panel holding every link — in the Ad On Group skin
 * rather than the campaign page's dark one.
 *
 * That means the horizontal About and Divisions links are gone from desktop.
 * It is a real change and a deliberate one: it is what "identical to the sales
 * page" means, and it is now the same bar everywhere instead of two.
 *
 * Two page sources, as usual on this site:
 *   public/**\/index.html      the flattened design pages (41 carry the nav)
 *   src/_includes/partials/    the Eleventy template pages
 *
 * The campaign page is skipped. It already has this nav in its own theme, built
 * by build-campaign-header.js, and it is out of scope by standing instruction.
 *
 * Idempotent. Usage:  node scripts/apply-nav.js [--dry]
 */
const fs = require("fs");
const path = require("path");
const { navMarkup, NAV_JS, MENU } = require("./lib/nav");

const ROOT = path.join(__dirname, "..");
const DRY = process.argv.includes("--dry");
const NAV = navMarkup("aog");

/** The campaign page keeps its own skin and is not ours to restyle here. */
const SKIP = ["public/ai-training/index.html"];

const files = [];
(function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const f = path.join(dir, e.name);
    if (e.isDirectory()) walk(f);
    else if (e.name === "index.html") files.push(f);
  }
})(path.join(ROOT, "public"));

let replaced = 0, already = 0, skipped = 0, noNav = 0;

for (const file of files) {
  const rel = path.relative(ROOT, file);
  if (SKIP.some((s) => rel === s)) { skipped++; continue; }

  let html = fs.readFileSync(file, "utf8");
  const at = html.indexOf("<nav data-aog-header");
  if (at === -1) { noNav++; continue; }

  const end = html.indexOf("</nav>", at);
  if (end === -1) { console.error(`  ⚠ unterminated <nav> in ${rel}`); continue; }
  const oldNav = html.slice(at, end + 6);

  if (oldNav === NAV && html.includes('id="aog-header-js"')) { already++; continue; }

  html = html.slice(0, at) + NAV + html.slice(end + 6);

  // One copy of the script, replaced rather than stacked on a re-run.
  html = html.replace(/<script id="aog-header-js">[\s\S]*?<\/script>/, "");
  const bodyEnd = html.lastIndexOf("</body>");
  if (bodyEnd === -1) { console.error(`  ⚠ no </body> in ${rel}`); continue; }
  html = html.slice(0, bodyEnd) + NAV_JS + html.slice(bodyEnd);

  if (!DRY) fs.writeFileSync(file, html);
  replaced++;
}

// The Eleventy partial, so template-built pages get the same bar.
const PARTIAL = path.join(ROOT, "src", "_includes", "partials", "header.njk");
const COMMENT = `{#
  Shared site header — generated by scripts/apply-nav.js from scripts/lib/nav.js.

  Edit lib/nav.js, not this file: the same definition also produces the campaign
  page's bar, and the point of it is that the two cannot drift apart again.

  This is the toggle navigation, in the Ad On Group skin. The horizontal About
  and Divisions dropdowns it replaced are now inside the panel, at every width.
  The toggle script is injected once per page alongside it.
#}
`;
let partialChanged = false;
if (fs.existsSync(PARTIAL)) {
  const next = COMMENT + NAV + "\n" + NAV_JS + "\n";
  if (fs.readFileSync(PARTIAL, "utf8") !== next) {
    if (!DRY) fs.writeFileSync(PARTIAL, next);
    partialChanged = true;
  }
}

console.log(`${DRY ? "[dry run] " : ""}Nav applied:`);
console.log(`   ${String(replaced).padStart(3)}  pages updated`);
console.log(`   ${String(already).padStart(3)}  already current`);
console.log(`   ${String(skipped).padStart(3)}  skipped (campaign page keeps its own skin)`);
console.log(`   ${String(noNav).padStart(3)}  pages with no header`);
console.log(`   partial: ${partialChanged ? "updated" : "unchanged"}`);
console.log(`   menu: ${MENU.reduce((n, g) => n + g[1].length, 0)} links in ${MENU.length} groups, plus phone and Contact`);
